### PR TITLE
Added Z390-UD

### PR DESCRIPTION
**Pull request by yooouuri**
Without Intel HD 630 enabled (used a MSI Armor 4GB RX570)

### CODE REVIEW

**Comment by yooouuri** [comment]
3. I can't disable CFG Lock in my bios so I think this one is necessary.
4. What does this `darkwake` boot flag?

I'll update my PR when I come back home.

**Comment by ZISQO** [comment]
@yooouuri 
3. most Z390 motherboard was supported disabled MSR Lock
4. 0 is disabled powernap, 8 is enabled powernap but recommended disabled

**Comment by yooouuri** [comment]
@ZISQO I need to set AppleCpuPmCfgLock to true, to get sleep working.

So both AppleCpuPmCfgLock and AppleXcpmCfgLock needs to be true.

**Comment by ZISQO** [comment]
@yooouuri 
what about trying with a PLUG.AML? and never turn it on both.
and you'd rather test with clover bootloader without AppleCpuPmCfgLock option.

because AppleCpuPmCfgLock option for 1st - 2nd gerneration.
and your cpu gen type was 8 or 9 then they don't need an option after 3rd generation.

just enabled one.

**Comment by yooouuri** [comment]
@ZISQO weird thing is, I changed AppleCpuPmCfgLock to false

1. changed AppleCpuPmCfgLock to false, no sleep, wakes up instantly...
2. changed AppleCpuPmCfgLock to true, sleep working
3. changed AppleCpuPmCfgLock to false, sleep still working.... SO WEIRD haha

Thanks anyway!

**Comment by ZISQO** [comment]
@yooouuri 
i think you'd better to test with Clover bootloader : )

**Comment by yooouuri** [comment]
Added drivers and OC 0.4 (commit e611445)

**Comment by yooouuri** [comment]
Found the issue why I had problems with sleep

```
pid 7969(LeagueClientUx): [0x0000c18200019196] 07:23:18 NoIdleSleepAssertion named: "Playing audio"
pid 7969(LeagueClientUx): [0x0000c18100059193] 07:23:19 NoDisplaySleepAssertion named: "Playing video"
```

Why is my PR declined, maybe a reason would be nice

**Comment by MacProDude** [comment]
Resubmit, I didn't see the request

**Comment by yooouuri** [comment]
see #73

**Pull request closed without merging**
